version: '3.8'

services:
  react:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:80
    environment:
      - NODE_ENV=development
    restart: unless-stopped
