[tool.poetry]
authors = ["ibqn"]
description = ""
name = "react-todos"
version = "0.1.0"

[tool.poetry.dependencies]
docker-compose = "^1.28.4"
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
